# Based on Linear Algebra Review and Reference, Zico Kolter (updated by Chuong Do)

In [2]:
import numpy as np

## Basic Notation

A linear equation has two or more variables that give a straight line when plotted. It has the form $a_1x_1+...+a_nx_n+c=0$. In matrix notation, $Ax=b$, where matrix $A$ is the variable-associated coefficients $a_n$ of the linear equations, $x$ is a matrix of the variables $x_n$, and $b$ is a matrix of the intercepts $c$.



In [2]:
np.array([(1,2,3), (4,5,6)])

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
np.array([(1,2,3), (4,5,6), (14,14,14)])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [14, 14, 14]])

$A\in \mathbb{R}^{m\times n}$ The matrix $A$ in in the set of real numbers, arranged in a matrix with $m$ rows and $n$ columns. Matrix elements are specified as $A_{ij}$, where $i$ is the row and $j$ is the column.

$x\in \mathbb{R}^{n}$ is a vector with $n$ entries. By convention, this is a column vector. A row vector is expressed by $x^T$, the transpose of $x$. Elements of $x$ are specified by $x_i$.

## Matrix Multiplication

The product of two matrices $A\in \mathbb{R}^{m\times n}$ and $B\in \mathbb{R}^{n\times p}$ is the matrix $C= AB\in \mathbb{R}^{m\times p}$, where

$$C_{ij}=\sum_{k=1}^n A_{ik}B_{kj}.$$
 
The number of columns in $A$ is equal to the number of rows in $B$. $C$ has the same number of rows as $A$ and columns as $B$. The calculation moves through $A$ by row and $B$ by colum as $i$ and $j$ iterate. E.g., each element of first row of $A$ is multiplied by the corresponding element of the first column of $B$. Per the summation interating from 1 to $n$, those values are then added together, producing the first row and column element of $C$.

In [4]:
a = [[1, 2, 3], 
     [4, 5, 6]]
b = [[1, 2], 
     [3, 4],
     [5, 6]]
np.matmul(a, b)

array([[22, 28],
       [49, 64]])

It is not, in general, commutative.

In [5]:
np.matmul(b, a)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

Remember, a vector is by convention a column vector.

In [6]:
a = [[1, 2], 
     [3, 4]]
b = [1, 2]
np.matmul(a, b)

array([ 5, 11])

In [7]:
np.matmul(b, a)

array([ 7, 10])

### Vector-Vector Products

#### Inner Product

The multiplication of two vectors of the same length, $x\in \mathbb{R}^n$ and $y\in \mathbb{R}^n$ is the *inner product* or *dot product*. Multiplication occurrs as

$$x^Ty=\sum_{i=1}^n x_iy_i.$$

The corresponding vector elements are multiplied, and those values are added together. The inner product is communicative, $x^Ty = y^Tx$.

In [3]:
x = [1,2,3]
y = [4,5,6]
np.matmul(x, y)

32

In [5]:
np.matmul(y, x)

32

#### Outer Product